project_name: build-xally-wind

before:
  hooks:
    - go mod tidy
builds:
  - id: server
    main: ./cmd/server/main.go
    binary: xally_server
    ldflags:
      - -w -s
    tags:
      - release
      - embed_frontend
    env:
      - VERSION="0.1.4"
      - GO_VERSION="1.20.1"
      - CGO_ENABLED=0
      - GIT_COMMIT="unknown"
      - BUILD_TIME="unknown"
      - BUILD_USER="unknown"
    goos:
      - windows
    goarch:
      - amd64
      # - arm64

  - id: client
    main: ./cmd/client/main.go
    binary: xally
    ldflags:
      - -w -s
    tags:
      - release
    env:
      - VERSION="0.1.4"
      - GO_VERSION="1.20.1"
      - CGO_ENABLED=1
      - GIT_COMMIT="unknown"
      - BUILD_TIME="unknown"
      - BUILD_USER="unknown"
    goos:
      - windows
    goarch:
      - amd64
      # - arm64
    overrides:
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          # - CXX=x86_64-w64-mingw32-g++
        ldflags:
          - -s
          - -w
        flags:
          - -trimpath
          - -mod=readonly
          - -buildmode=pie
      # - goos: windows
      #   goarch: arm64
      #   env:
      #     - CC=arm-linux-gnueabihf-gcc
      #     # - CXX=arm-linux-gnueabihf-g++
      #   ldflags:
      #     - -s
      #     - -w
      #   flags:
      #     - -trimpath
      #     - -mod=readonly
      #     - -buildmode=pie

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    builds:
      - server
      - client
    name_template: "xally_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
snapshot:
  name_template: "{{ incpatch .Version }}-next"