# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: xally
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - id: client-darwin
    main: ./cmd/client/main.go
    binary: xally
    # goarch:
    #   - arm64
    goos:
      - darwin
    ignore:
    - goos: darwin
      goarch: "386"
    env:
      - CC=/home/runner/work/osxcross/target/bin/oa64-clang
      - CXX=/home/runner/work/osxcross/target/bin/oa64-clang++
    flags:
      - "-mod=readonly"
      - -trimpath
    ldflags: >
      -linkmode external
      -extldflags "-static"

  - id: client-linux-amd64
    main: ./cmd/client/main.go
    binary: xally
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    flags:
      # - "-mod={{ .Env.MOD }}"
      # - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      # - "{{ .Env.BUILD_VARS }}"
      # - "{{ .Env.STRIP_FLAGS }}"
      # - "-linkmode={{ .Env.LINKMODE }}"
      - -extldflags "-lc -lrt -lpthread --static"

  - id: client-linux-arm64
    main: ./cmd/client/main.go
    binary: xally
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      # - "-mod={{ .Env.MOD }}"
      # - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      # - "{{ .Env.BUILD_VARS }}"
      # - "{{ .Env.STRIP_FLAGS }}"
      # - "-linkmode={{ .Env.LINKMODE }}"
      - -extldflags "-lc -lrt -lpthread --static"

  - id: client-windows-amd64
    main: ./cmd/client/main.go
    binary: xally
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      # - "-mod={{ .Env.MOD }}"
      # - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
      - -buildmode=exe
    # ldflags:
    #   - "{{ .Env.BUILD_VARS }}"
    #   - "{{ .Env.STRIP_FLAGS }}"
    #   - "-linkmode={{ .Env.LINKMODE }}"

  - id: server
    main: ./cmd/server/main.go
    binary: xally_server
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
release:
  prerelease: auto

universal_binaries:
  - replace: true

archives:
  - id: xally-archive
    format: tar.gz
    rlcp: true
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
- ids:
    - xally-archive
  tap:
    owner: robinmin
    name: homebrew-tap
  folder: Formula
  commit_author:
    name: robinmin
    email: minlongbing@gmail.com
  homepage: https://github.com/robinmin/xally
  description: >-
    X-Ally is an AI-based TUI (aka Terminal User Interface) tool that helps people do things more elegantly.
  license: GPL-3.

scoop:
  bucket:
    owner: robinmin
    name: scoop-bucket
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com
  folder: bucket
  homepage: https://github.com/robinmin/xally
  description: >-
    X-Ally is an AI-based TUI (aka Terminal User Interface) tool that helps people do things more elegantly.
  license: GPL-3.

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
