project_name: release-xally

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  mode: append
  extra_files:
    - glob: ./xally-build/**/*
    - glob: ./xally-build/checksums.txt
  name_template: "Release {{.Tag}}"
  header: |
    # What's Changed

    ## 🚀 Features

    ## 🎄 Enhancements

    ## 🎠 Community

    ## New Contributors

    ## Code Diff

brews:
- ids:
    - xally-archive
  tap:
    owner: robinmin
    name: homebrew-tap
  folder: Formula
  commit_author:
    name: robinmin
    email: minlongbing@gmail.com
  homepage: https://github.com/robinmin/xally
  description: >-
    X-Ally is an AI-based TUI (aka Terminal User Interface) tool that helps people do things more elegantly.
  license: GPL-3.

scoop:
  bucket:
    owner: robinmin
    name: scoop-bucket
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com
  folder: bucket
  homepage: https://github.com/robinmin/xally
  description: >-
    X-Ally is an AI-based TUI (aka Terminal User Interface) tool that helps people do things more elegantly.
  license: GPL-3.