name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
          cache: true
      - name: OSXCross for CGO Support
        run: |
          mkdir ../../osxcross
          git clone https://github.com/plentico/osxcross-target.git ../../osxcross/target
      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          # Custom secret here since we need to access to robinmin/homebrew-tap and robinmin/scoop-bucket repo.
          GITHUB_TOKEN: ${{ secrets.PBLSH_TOKEN }}
          SCOOP_TOKEN: ${{ secrets.PBLSH_TOKEN }}
